import {Add,CategoryOutlined} from "@mui/icons-material";
import {Alert,Box,Button,Dialog,DialogActions,DialogContent,DialogTitle,MenuItem,Paper,Stack,Tab,Tabs,TextField,Typography} from "@mui/material";
import {useEffect,useState} from "react";
import {api} from "../../Services/api";

type Item={id:number;nome:string;marca_id?:number;descricao?:string;telefone?:string;email?:string;documento?:string;endereco?:string};
const titles=["marca","modelo","serviço","atendente","cliente"];

export function CadastrosReal(){
  const [tab,setTab]=useState(0),[marcas,setMarcas]=useState<Item[]>([]),[modelos,setModelos]=useState<Item[]>([]),[servicos,setServicos]=useState<Item[]>([]),[atendentes,setAtendentes]=useState<Item[]>([]),[clientes,setClientes]=useState<Item[]>([]);
  const [open,setOpen]=useState(false),[erro,setErro]=useState(""),[nome,setNome]=useState(""),[descricao,setDescricao]=useState(""),[marcaId,setMarcaId]=useState(""),[telefone,setTelefone]=useState(""),[email,setEmail]=useState(""),[documento,setDocumento]=useState(""),[endereco,setEndereco]=useState("");
  async function load(){try{const [a,b,c,d,e]=await Promise.all([api.get("/marcas"),api.get("/modelos"),api.get("/servicos"),api.get("/atendentes"),api.get("/clientes")]);setMarcas(a.data);setModelos(b.data);setServicos(c.data);setAtendentes(d.data);setClientes(e.data)}catch(e:any){setErro(e.response?.data?.erro||"Não foi possível carregar os cadastros")}}
  useEffect(()=>{load()},[]);
  function novo(){setNome("");setDescricao("");setMarcaId("");setTelefone("");setEmail("");setDocumento("");setEndereco("");setErro("");setOpen(true)}
  async function save(){try{if(!nome.trim()||(tab===1&&!marcaId))return setErro("Preencha os campos obrigatórios");if(tab===0)await api.post("/marcas",{nome});if(tab===1)await api.post("/modelos",{nome,marca_id:Number(marcaId)});if(tab===2)await api.post("/servicos",{nome,descricao,preco:0,custo:0});if(tab===3)await api.post("/atendentes",{nome,telefone:telefone||null,email:email||null});if(tab===4)await api.post("/clientes",{nome,telefone:telefone||null,email:email||null,documento:documento||null,endereco:endereco||null});setOpen(false);await load()}catch(e:any){setErro(e.response?.data?.erro||"Não foi possível salvar")}}
  const data=[marcas,modelos,servicos,atendentes,clientes][tab];
  return <Stack spacing={3}>
    <Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between"><Box><Typography variant="h4" fontWeight={800}>Cadastros</Typography><Typography color="text.secondary">Marcas, modelos, serviços, atendentes e clientes da empresa.</Typography></Box><Button variant="contained" startIcon={<Add/>} onClick={novo}>Novo {titles[tab]}</Button></Stack>
    {erro&&!open&&<Alert severity="error">{erro}</Alert>}
    <Paper sx={{border:"1px solid #e2e9e5",borderRadius:3,overflow:"hidden"}}><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable" sx={{px:2,borderBottom:"1px solid #edf1ef"}}><Tab label="Marcas"/><Tab label="Modelos"/><Tab label="Serviços"/><Tab label="Atendentes"/><Tab label="Clientes"/></Tabs><Box sx={{p:2}}>{data.length===0?<Box sx={{py:8,textAlign:"center",color:"text.secondary"}}><CategoryOutlined sx={{fontSize:48,opacity:.35}}/><Typography>Nenhum cadastro encontrado</Typography></Box>:data.map(i=><Stack key={i.id} sx={{p:2,borderBottom:"1px solid #edf1ef"}}><Typography fontWeight={750}>{i.nome}</Typography>{tab===1&&<Typography fontSize={12} color="text.secondary">Marca: {marcas.find(m=>m.id===i.marca_id)?.nome||"—"}</Typography>}{tab===2&&i.descricao&&<Typography fontSize={12} color="text.secondary">{i.descricao}</Typography>}{tab>=3&&<Typography fontSize={12} color="text.secondary">{[i.telefone,i.email,tab===4?i.documento:null].filter(Boolean).join(" • ")||"Sem dados de contato"}</Typography>}</Stack>)}</Box></Paper>
    <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Novo {titles[tab]}</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{erro&&<Alert severity="error">{erro}</Alert>}{tab===1&&<TextField select label="Marca" required value={marcaId} onChange={e=>setMarcaId(e.target.value)}>{marcas.map(m=><MenuItem key={m.id} value={m.id}>{m.nome}</MenuItem>)}</TextField>}<TextField label="Nome" required value={nome} onChange={e=>setNome(e.target.value)}/>{tab===2&&<TextField label="Descrição" multiline rows={3} value={descricao} onChange={e=>setDescricao(e.target.value)} helperText="O valor será informado somente no pagamento da OS"/>}{tab>=3&&<><TextField label="Telefone" value={telefone} onChange={e=>setTelefone(e.target.value)}/><TextField label="E-mail" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></>}{tab===4&&<><TextField label="CPF/CNPJ" value={documento} onChange={e=>setDocumento(e.target.value)}/><TextField label="Endereço" value={endereco} onChange={e=>setEndereco(e.target.value)}/></>}</Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="contained" onClick={save}>Salvar</Button></DialogActions></Dialog>
  </Stack>
}
