import {Add,CategoryOutlined,DeleteOutline,EditOutlined} from "@mui/icons-material";
import {Alert,Box,Button,Dialog,DialogActions,DialogContent,DialogTitle,IconButton,MenuItem,Paper,Stack,Tab,Tabs,TextField,Tooltip,Typography} from "@mui/material";
import {useEffect,useState} from "react";
import {api} from "../../Services/api";
type Item={id:number;nome:string;marca_id?:number;descricao?:string;telefone?:string;email?:string;documento?:string;endereco?:string};
const titles=["marca","modelo","serviço","atendente","cliente"],routes=["marcas","modelos","servicos","atendentes","clientes"];
export function CadastrosReal(){
 const [tab,setTab]=useState(0),[lists,setLists]=useState<Item[][]>([[],[],[],[],[]]),[open,setOpen]=useState(false),[editing,setEditing]=useState<Item|null>(null),[erro,setErro]=useState(""),[nome,setNome]=useState(""),[descricao,setDescricao]=useState(""),[marcaId,setMarcaId]=useState(""),[telefone,setTelefone]=useState(""),[email,setEmail]=useState(""),[documento,setDocumento]=useState(""),[endereco,setEndereco]=useState("");
 const marcas=lists[0],data=lists[tab];
 async function load(){try{const r=await Promise.all(routes.map(x=>api.get(`/${x}`)));setLists(r.map(x=>x.data))}catch(e:any){setErro(e.response?.data?.erro||"Não foi possível carregar os cadastros")}}
 useEffect(()=>{load()},[]);
 function clear(){setNome("");setDescricao("");setMarcaId("");setTelefone("");setEmail("");setDocumento("");setEndereco("");setErro("")}
 function novo(){clear();setEditing(null);setOpen(true)}
 function editar(i:Item){clear();setEditing(i);setNome(i.nome);setDescricao(i.descricao||"");setMarcaId(String(i.marca_id||""));setTelefone(i.telefone||"");setEmail(i.email||"");setDocumento(i.documento||"");setEndereco(i.endereco||"");setOpen(true)}
 function body(){if(tab===0)return {nome};if(tab===1)return {nome,marca_id:Number(marcaId)};if(tab===2)return {nome,descricao};if(tab===3)return {nome,telefone:telefone||null,email:email||null};return {nome,telefone:telefone||null,email:email||null,documento:documento||null,endereco:endereco||null}}
 async function save(){try{if(!nome.trim()||(tab===1&&!marcaId))return setErro("Preencha os campos obrigatórios");if(editing)await api.patch(`/${routes[tab]}/${editing.id}`,body());else await api.post(`/${routes[tab]}`,tab===2?{...body(),preco:0,custo:0}:body());setOpen(false);await load()}catch(e:any){setErro(e.response?.data?.erro||"Não foi possível salvar")}}
 async function excluir(i:Item){if(!window.confirm(`Excluir ${titles[tab]} “${i.nome}”?`))return;try{await api.delete(`/${routes[tab]}/${i.id}`);await load()}catch(e:any){setErro(e.response?.data?.erro||"Não foi possível excluir")}}
 return <Stack spacing={3}><Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between"><Box><Typography variant="h4" fontWeight={800}>Cadastros</Typography><Typography color="text.secondary">Marcas, modelos, serviços, atendentes e clientes da empresa.</Typography></Box><Button variant="contained" startIcon={<Add/>} onClick={novo}>Novo {titles[tab]}</Button></Stack>{erro&&!open&&<Alert severity="error">{erro}</Alert>}
 <Paper sx={{border:"1px solid #e2e9e5",borderRadius:3,overflow:"hidden"}}><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable" sx={{px:2,borderBottom:"1px solid #edf1ef"}}><Tab label="Marcas"/><Tab label="Modelos"/><Tab label="Serviços"/><Tab label="Atendentes"/><Tab label="Clientes"/></Tabs><Box sx={{p:2}}>{data.length===0?<Box sx={{py:8,textAlign:"center",color:"text.secondary"}}><CategoryOutlined sx={{fontSize:48,opacity:.35}}/><Typography>Nenhum cadastro encontrado</Typography></Box>:data.map(i=><Stack direction="row" alignItems="center" key={i.id} sx={{p:2,borderBottom:"1px solid #edf1ef"}}><Box flex={1}><Typography fontWeight={750}>{i.nome}</Typography>{tab===1&&<Typography fontSize={12} color="text.secondary">Marca: {marcas.find(m=>m.id===i.marca_id)?.nome||"—"}</Typography>}{tab===2&&i.descricao&&<Typography fontSize={12} color="text.secondary">{i.descricao}</Typography>}{tab>=3&&<Typography fontSize={12} color="text.secondary">{[i.telefone,i.email,tab===4?i.documento:null].filter(Boolean).join(" • ")||"Sem dados de contato"}</Typography>}</Box><Tooltip title="Editar"><IconButton onClick={()=>editar(i)}><EditOutlined/></IconButton></Tooltip><Tooltip title="Excluir"><IconButton color="error" onClick={()=>excluir(i)}><DeleteOutline/></IconButton></Tooltip></Stack>)}</Box></Paper>
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{editing?"Editar":"Novo"} {titles[tab]}</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{erro&&<Alert severity="error">{erro}</Alert>}{tab===1&&<TextField select label="Marca" required value={marcaId} onChange={e=>setMarcaId(e.target.value)}>{marcas.map(m=><MenuItem key={m.id} value={m.id}>{m.nome}</MenuItem>)}</TextField>}<TextField label="Nome" required value={nome} onChange={e=>setNome(e.target.value)}/>{tab===2&&<TextField label="Descrição" multiline rows={3} value={descricao} onChange={e=>setDescricao(e.target.value)}/>} {tab>=3&&<><TextField label="Telefone" value={telefone} onChange={e=>setTelefone(e.target.value)}/><TextField label="E-mail" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></>}{tab===4&&<><TextField label="CPF/CNPJ" value={documento} onChange={e=>setDocumento(e.target.value)}/><TextField label="Endereço" value={endereco} onChange={e=>setEndereco(e.target.value)}/></>}</Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="contained" onClick={save}>Salvar</Button></DialogActions></Dialog></Stack>
}
