import {Add,Inventory2Outlined,SwapVert} from "@mui/icons-material";
import {Alert,Box,Button,Card,Chip,Dialog,DialogActions,DialogContent,DialogTitle,Grid,MenuItem,Stack,TextField,Typography} from "@mui/material";
import {useEffect,useMemo,useState} from "react";
import {api} from "../Services/api";

type Insumo={id:number;sku:string;nome:string;unidade:string;estoque:number;estoque_minimo:number;custo_medio:number;preco_venda:number;ativo:boolean};
const dinheiro=(v:number)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export function InventoryReal(){
 const [items,setItems]=useState<Insumo[]>([]),[q,setQ]=useState(""),[erro,setErro]=useState(""),[novo,setNovo]=useState(false),[movItem,setMovItem]=useState<Insumo|null>(null);
 const [form,setForm]=useState({sku:"",nome:"",unidade:"UN",estoque:"0",estoque_minimo:"0",custo_medio:"0",preco_venda:"0"}),[mov,setMov]=useState({tipo:"ENTRADA",quantidade:"",motivo:"",referencia:""});
 async function load(){try{setItems((await api.get("/insumos")).data)}catch(e:any){setErro(e.response?.data?.erro||"Não foi possível carregar os insumos")}}
 useEffect(()=>{load()},[]);
 const data=useMemo(()=>items.filter(i=>`${i.nome} ${i.sku}`.toLowerCase().includes(q.toLowerCase())),[items,q]);
 const zerados=useMemo(()=>items.filter(i=>Number(i.estoque)===0),[items]);
 async function salvar(){try{if(!form.sku.trim()||!form.nome.trim())return setErro("Informe o SKU e o nome");await api.post("/insumos",{...form,estoque:Number(form.estoque),estoque_minimo:Number(form.estoque_minimo),custo_medio:Number(form.custo_medio),preco_venda:Number(form.preco_venda),ativo:true});setNovo(false);await load()}catch(e:any){setErro(e.response?.data?.erro||"Não foi possível salvar o insumo")}}
 async function movimentar(){if(!movItem)return;try{await api.post(`/insumos/${movItem.id}/movimentos`,{...mov,quantidade:Number(mov.quantidade)});setMovItem(null);await load()}catch(e:any){setErro(e.response?.data?.erro||"Não foi possível movimentar o estoque")}}
 return <Stack spacing={3}>
  <Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between"><Box><Typography variant="h4" fontWeight={800}>Insumos e estoque</Typography><Typography color="text.secondary">Cadastre itens e controle entradas, saídas e estoque mínimo.</Typography></Box><Button variant="contained" startIcon={<Add/>} onClick={()=>{setErro("");setForm({sku:"",nome:"",unidade:"UN",estoque:"0",estoque_minimo:"0",custo_medio:"0",preco_venda:"0"});setNovo(true)}}>Novo insumo</Button></Stack>
  {erro&&<Alert severity="error" onClose={()=>setErro("")}>{erro}</Alert>}
  {zerados.length>0&&<Alert severity="warning"><b>Estoque zerado:</b> {zerados.map(i=>i.nome).join(", ")}. Faça uma entrada para repor {zerados.length===1?"este item":"estes itens"}.</Alert>}
  <TextField size="small" placeholder="Buscar por nome ou SKU" value={q} onChange={e=>setQ(e.target.value)} sx={{maxWidth:420}}/>
  <Grid container spacing={2}>{data.map(i=>{const critico=Number(i.estoque)<=Number(i.estoque_minimo);return <Grid size={{xs:12,md:6}} key={i.id}><Card variant="outlined" sx={{p:2.5,borderRadius:3}}><Stack direction="row" gap={2}><Box sx={{width:48,height:48,bgcolor:"#edf6f1",color:"#278662",display:"grid",placeItems:"center",borderRadius:2,flexShrink:0}}><Inventory2Outlined/></Box><Box flex={1}><Stack direction="row" justifyContent="space-between" gap={1}><Typography fontWeight={800}>{i.nome}</Typography><Chip size="small" color={critico?"error":"success"} label={`${i.estoque} ${i.unidade}`}/></Stack><Typography fontSize={12} color="text.secondary">SKU {i.sku} • Mínimo {i.estoque_minimo} {i.unidade}</Typography><Typography fontSize={12} mt={.5}>Custo {dinheiro(i.custo_medio)} • Venda {dinheiro(i.preco_venda)}</Typography><Button size="small" startIcon={<SwapVert/>} sx={{mt:1}} onClick={()=>{setErro("");setMov({tipo:"ENTRADA",quantidade:"",motivo:"",referencia:""});setMovItem(i)}}>Movimentar estoque</Button></Box></Stack></Card></Grid>})}</Grid>
  <Dialog open={novo} onClose={()=>setNovo(false)} fullWidth maxWidth="sm"><DialogTitle>Novo insumo</DialogTitle><DialogContent><Grid container spacing={2} mt={1}><Grid size={{xs:12,sm:6}}><TextField fullWidth required label="SKU / Código" value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/></Grid><Grid size={{xs:12,sm:6}}><TextField fullWidth required label="Nome" value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></Grid><Grid size={{xs:12,sm:4}}><TextField fullWidth label="Unidade" value={form.unidade} onChange={e=>setForm({...form,unidade:e.target.value})}/></Grid><Grid size={{xs:12,sm:4}}><TextField fullWidth type="number" label="Estoque inicial" value={form.estoque} onChange={e=>setForm({...form,estoque:e.target.value})}/></Grid><Grid size={{xs:12,sm:4}}><TextField fullWidth type="number" label="Estoque mínimo" value={form.estoque_minimo} onChange={e=>setForm({...form,estoque_minimo:e.target.value})}/></Grid><Grid size={{xs:12,sm:6}}><TextField fullWidth type="number" label="Custo médio" value={form.custo_medio} onChange={e=>setForm({...form,custo_medio:e.target.value})}/></Grid><Grid size={{xs:12,sm:6}}><TextField fullWidth type="number" label="Preço de venda" value={form.preco_venda} onChange={e=>setForm({...form,preco_venda:e.target.value})}/></Grid></Grid></DialogContent><DialogActions><Button onClick={()=>setNovo(false)}>Cancelar</Button><Button variant="contained" onClick={salvar}>Salvar</Button></DialogActions></Dialog>
  <Dialog open={!!movItem} onClose={()=>setMovItem(null)} fullWidth maxWidth="sm"><DialogTitle>Movimentar • {movItem?.nome}</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField select label="Tipo" value={mov.tipo} onChange={e=>setMov({...mov,tipo:e.target.value})}><MenuItem value="ENTRADA">Entrada</MenuItem><MenuItem value="SAIDA">Saída</MenuItem><MenuItem value="AJUSTE">Ajuste de saldo</MenuItem></TextField><TextField required type="number" label={mov.tipo==="AJUSTE"?"Novo saldo":"Quantidade"} value={mov.quantidade} onChange={e=>setMov({...mov,quantidade:e.target.value})}/><TextField required label="Motivo" value={mov.motivo} onChange={e=>setMov({...mov,motivo:e.target.value})}/><TextField label="Referência / documento" value={mov.referencia} onChange={e=>setMov({...mov,referencia:e.target.value})}/></Stack></DialogContent><DialogActions><Button onClick={()=>setMovItem(null)}>Cancelar</Button><Button variant="contained" onClick={movimentar}>Confirmar</Button></DialogActions></Dialog>
 </Stack>
}
