import { Add, ArrowDownward, ArrowUpward, BuildOutlined, CheckCircleOutline, Inventory2Outlined, MoreHoriz, PointOfSaleOutlined, Search } from "@mui/icons-material";
import { Box, Button, Card, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Grid, IconButton, InputAdornment, LinearProgress, MenuItem, Paper, Stack, Tab, Tabs, TextField, Tooltip as MuiTooltip, Typography } from "@mui/material";
import { useEffect, useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api } from "../Services/api";

const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
type OverviewOrder={id:number;numero:string;cliente:string;modelo:string;marca:string;servico:string;situacao:string;valor:number;custo:number;valor_pago?:number;pago?:boolean;data_hora?:string};
type ZeroStock={id:number;sku:string;nome:string;modelo?:string;estoque:number;unidade:string};
const stock = [
  { nome: "Tela iPhone 14 Pro OLED", sku: "TEL-IP14P", qtd: 3, min: 5, custo: 690 },
  { nome: "Conector USB-C Samsung", sku: "CON-SAM-03", qtd: 4, min: 8, custo: 38 },
  { nome: "Bateria Moto G84", sku: "BAT-MG84", qtd: 2, min: 4, custo: 92 },
  { nome: "Álcool isopropílico 1L", sku: "INS-ALC-01", qtd: 12, min: 5, custo: 29.9 },
];
const chart = [{ n: "Jan", v: 18200 }, { n: "Fev", v: 21400 }, { n: "Mar", v: 19800 }, { n: "Abr", v: 24600 }, { n: "Mai", v: 27300 }, { n: "Jun", v: 25900 }, { n: "Jul", v: 31450 }];

const statusColor = (s: string) => s === "Finalizado" ? "success" : s === "Pendente" ? "warning" : s === "Manutenção" ? "info" : "default";
const panel = { border: "1px solid #e2e9e5", borderRadius: 3, boxShadow: "0 3px 14px rgba(28,60,47,.04)" };

export function Overview() {
  const [orders,setOrders]=useState<OverviewOrder[]>([]);
  const [insumosZerados,setInsumosZerados]=useState<ZeroStock[]>([]),[zeroOpen,setZeroOpen]=useState(false);
  const [periodo,setPeriodo]=useState("semanal");
  useEffect(()=>{Promise.all([api.get("/os"),api.get("/insumos")]).then(([o,i])=>{setOrders(o.data);setInsumosZerados(i.data.filter((x:ZeroStock)=>Number(x.estoque)<=0))}).catch(()=>{setOrders([]);setInsumosZerados([])})},[]);
  function imprimirZerados(){const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"} as Record<string,string>)[c]!),w=window.open("","_blank","width=850,height=650");if(!w)return;w.document.write(`<html><head><title>Insumos zerados</title><style>body{font-family:Arial;padding:30px;color:#24372f}h1{font-size:22px}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #ddd;text-align:left}th{background:#f4f7f5;font-size:12px}</style></head><body><h1>Insumos com estoque zerado</h1><p>Emitido em ${esc(new Date().toLocaleString("pt-BR"))}</p><table><thead><tr><th>SKU</th><th>INSUMO</th><th>MODELO</th><th>ESTOQUE</th></tr></thead><tbody>${insumosZerados.map(i=>`<tr><td>${esc(i.sku)}</td><td>${esc(i.nome)}</td><td>${esc(i.modelo||"—")}</td><td>${esc(i.estoque)} ${esc(i.unidade)}</td></tr>`).join("")}</tbody></table><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
  const dashboard=useMemo(()=>{
    const dias:{[key:string]:number}={diario:1,semanal:7,mensal:30,trimestral:90,semestral:180,anual:365};
    const totalDias=dias[periodo]||7,agora=new Date(),inicio=new Date(agora);inicio.setHours(0,0,0,0);inicio.setDate(inicio.getDate()-totalDias+1);
    const filtradas=orders.filter(o=>o.data_hora&&new Date(o.data_hora)>=inicio);
    const finalizadas=filtradas.filter(o=>o.situacao==="Finalizado"),abertas=filtradas.filter(o=>o.situacao!=="Finalizado");
    const faturamento=filtradas.filter(o=>o.pago).reduce((s,o)=>s+Number(o.valor_pago||o.valor||0),0);
    const passo=Math.max(1,Math.ceil(totalDias/12)),barras=[] as {nome:string;faturamento:number;finalizadas:number}[];
    for(let i=0;i<totalDias;i+=passo){const de=new Date(inicio);de.setDate(de.getDate()+i);const ate=new Date(de);ate.setDate(ate.getDate()+passo);const grupo=filtradas.filter(o=>{const d=new Date(o.data_hora!);return d>=de&&d<ate});barras.push({nome:de.toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"}),faturamento:grupo.filter(o=>o.pago).reduce((s,o)=>s+Number(o.valor_pago||o.valor||0),0),finalizadas:grupo.filter(o=>o.situacao==="Finalizado").length})}
    const marcas=Object.entries(finalizadas.reduce((acc,o)=>{const marca=o.marca||"Sem marca";acc[marca]=(acc[marca]||0)+1;return acc},{} as Record<string,number>)).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([nome,total])=>({nome,total}));
    return {filtradas,finalizadas,abertas,faturamento,barras,marcas,entradas:abertas.filter(o=>o.situacao==="Entrada").length,garantias:abertas.filter(o=>o.situacao==="Garantia").length,pendencias:abertas.filter(o=>o.situacao==="Pendente").length};
  },[orders,periodo]);
  return <Stack spacing={3}>
    <Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between" gap={2}><Box><Typography variant="h4" fontWeight={800}>Visão Geral</Typography><Typography color="text.secondary">Indicadores operacionais e financeiros da sua empresa.</Typography></Box><TextField select size="small" label="Período" value={periodo} onChange={e=>setPeriodo(e.target.value)} sx={{minWidth:180}}>{[["diario","Diário"],["semanal","Semanal"],["mensal","Mensal"],["trimestral","Trimestral"],["semestral","Semestral"],["anual","Anual"]].map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField></Stack>
    <Grid container spacing={2}>
      <Metric title="Faturamento" value={money(dashboard.faturamento)} detail="Somente pagamentos confirmados" icon={<PointOfSaleOutlined />} positive />
      <Metric title="Ordens abertas" value={String(dashboard.abertas.length)} detail={`${dashboard.entradas} entradas • ${dashboard.garantias} garantias • ${dashboard.pendencias} pendências`} icon={<BuildOutlined />} />
      <Metric title="Finalizadas" value={String(dashboard.finalizadas.length)} detail={`No período ${periodo}`} icon={<CheckCircleOutline />} positive />
      <Metric title="Insumos zerados" value={String(insumosZerados.length)} detail="Clique no ícone para visualizar" icon={<Inventory2Outlined />} warning onClick={()=>setZeroOpen(true)} />
    </Grid>
    <Grid container spacing={3}>
      <Grid size={{xs:12,lg:4}}><DashboardChart title="Faturamento" subtitle="Valores pagos no período" data={dashboard.barras} dataKey="faturamento" color="#249a6a" currency/></Grid>
      <Grid size={{xs:12,lg:4}}><DashboardChart title="OS finalizadas" subtitle="Finalizações por período" data={dashboard.barras} dataKey="finalizadas" color="#3978d4"/></Grid>
      <Grid size={{xs:12,lg:4}}><DashboardChart title="Marcas mais finalizadas" subtitle="OS finalizadas por marca" data={dashboard.marcas} dataKey="total" color="#8b5cf6"/></Grid>
    </Grid>
    <OrderTable title="Ordens recentes" orders={dashboard.filtradas.slice(0,10)} />
    <Dialog open={zeroOpen} onClose={()=>setZeroOpen(false)} fullWidth maxWidth="md"><DialogTitle>Insumos com estoque zerado</DialogTitle><DialogContent><Box sx={{overflowX:"auto"}}><Box component="table" sx={{width:"100%",borderCollapse:"collapse",'& th':{bgcolor:"#f7f9f8",p:1.2,textAlign:"left",fontSize:11},'& td':{p:1.2,borderTop:"1px solid #edf1ef",fontSize:13}}><thead><tr><th>SKU</th><th>INSUMO</th><th>MODELO</th><th>ESTOQUE</th></tr></thead><tbody>{insumosZerados.length?insumosZerados.map(i=><tr key={i.id}><td><b>{i.sku}</b></td><td>{i.nome}</td><td>{i.modelo||"—"}</td><td><Chip size="small" color="error" label={`${i.estoque} ${i.unidade}`}/></td></tr>):<tr><td colSpan={4}>Nenhum insumo com estoque zerado.</td></tr>}</tbody></Box></Box></DialogContent><DialogActions><Button onClick={()=>setZeroOpen(false)}>Fechar</Button><Button variant="contained" onClick={imprimirZerados} disabled={!insumosZerados.length}>Imprimir lista</Button></DialogActions></Dialog>
  </Stack>;
}

function DashboardChart({title,subtitle,data,dataKey,color,currency}:{title:string;subtitle:string;data:any[];dataKey:string;color:string;currency?:boolean}){return <Paper sx={{...panel,p:2.5,height:330}}><Typography fontWeight={800} fontSize={17}>{title}</Typography><Typography fontSize={12} color="text.secondary">{subtitle}</Typography><Box sx={{height:245,mt:2}}><ResponsiveContainer><BarChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#edf1ef"/><XAxis dataKey="nome" axisLine={false} tickLine={false} fontSize={10}/><YAxis axisLine={false} tickLine={false} fontSize={10}/><Tooltip formatter={(v)=>currency?money(Number(v)):Number(v)} labelStyle={{color:"#32463d"}}/><Bar dataKey={dataKey} fill={color} radius={[5,5,0,0]} label={{position:"top",fontSize:10,fill:"#60736b",formatter:(v:any)=>currency?money(Number(v)):v}}/></BarChart></ResponsiveContainer></Box></Paper>}

function Metric({ title, value, detail, icon, positive, warning, onClick }: any) { return <Grid size={{ xs: 12, sm: 6, lg: 3 }}><Card sx={{ ...panel, p: 2.5 }}><Stack direction="row" justifyContent="space-between"><Box><Typography color="text.secondary" fontSize={13}>{title}</Typography><Typography fontWeight={800} fontSize={25} mt={.5}>{value}</Typography></Box>{onClick?<MuiTooltip title="Ver lista"><IconButton onClick={onClick} sx={{width:42,height:42,borderRadius:2,bgcolor:"#fff3e2",color:"#d07a18"}}>{icon}</IconButton></MuiTooltip>:<Box sx={{ width: 42, height: 42, borderRadius: 2, display: "grid", placeItems: "center", bgcolor: warning ? "#fff3e2" : "#e6f5ee", color: warning ? "#d07a18" : "#21865f" }}>{icon}</Box>}</Stack><Typography fontSize={11} color={positive ? "success.main" : warning ? "warning.main" : "text.secondary"} mt={1.5}>{positive && <ArrowUpward sx={{ fontSize: 12 }}/>} {detail}</Typography></Card></Grid> }

function OrderTable({ title = "Ordens de serviço",orders=[] }: { title?: string;orders?:OverviewOrder[] }) { return <Paper sx={{ ...panel, overflow: "hidden" }}><Stack direction={{ xs: "column", sm: "row" }} sx={{ p: 2.5 }} alignItems={{ sm: "center" }} gap={2}><Box><Typography fontWeight={800} fontSize={18}>{title}</Typography><Typography fontSize={12} color="text.secondary">Acompanhe os atendimentos da oficina</Typography></Box><TextField size="small" placeholder="Buscar OS ou cliente..." sx={{ ml: { sm: "auto" } }} slotProps={{ input: { startAdornment: <InputAdornment position="start"><Search fontSize="small"/></InputAdornment> } }}/><Button variant="contained" startIcon={<Add />}>Nova OS</Button></Stack><Box sx={{ overflowX: "auto" }}><Box component="table" sx={{ width: "100%", borderCollapse: "collapse", minWidth: 800, '& th': { bgcolor: "#f7f9f8", color: "#6a7e76", fontSize: 11, textAlign: "left", py: 1.4, px: 2.5 }, '& td': { borderTop: "1px solid #edf1ef", py: 1.6, px: 2.5, fontSize: 13 } }}><thead><tr><th>ORDEM</th><th>CLIENTE / MODELO</th><th>SERVIÇO</th><th>STATUS</th><th>VALOR</th><th>DATA</th><th></th></tr></thead><tbody>{orders.map(o => <tr key={o.id}><td><Typography fontSize={13} fontWeight={800} color="success.main">{o.numero}</Typography></td><td><b>{o.cliente}</b><br/><span style={{ color: "#778a82", fontSize: 12 }}>{o.modelo}</span></td><td>{o.servico}</td><td><Chip size="small" color={statusColor(o.situacao) as any} variant="outlined" label={o.situacao}/></td><td><b>{money(Number(o.valor||0))}</b><br/><span style={{color:"#778a82",fontSize:10}}>Custo: {money(Number(o.custo||0))}</span></td><td>{o.data_hora?new Date(o.data_hora).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"}):"—"}</td><td><IconButton size="small"><MoreHoriz/></IconButton></td></tr>)}</tbody></Box></Box></Paper> }

export function Orders() { return <Stack spacing={3}><PageTitle title="Ordens de serviço" subtitle="Cadastre, acompanhe e finalize os atendimentos."/><OrderTable /></Stack> }

export function Inventory() { const [query,setQuery]=useState(""); const data=useMemo(()=>stock.filter(i=>i.nome.toLowerCase().includes(query.toLowerCase())),[query]); return <Stack spacing={3}><PageTitle title="Insumos e estoque" subtitle="Controle entradas, saídas e níveis mínimos." action="Novo insumo"/><Paper sx={{...panel,p:2.5}}><TextField value={query} onChange={e=>setQuery(e.target.value)} size="small" placeholder="Buscar por nome ou SKU" slotProps={{input:{startAdornment:<InputAdornment position="start"><Search/></InputAdornment>}}}/><Grid container spacing={2} mt={1}>{data.map(i=><Grid size={{xs:12,md:6}} key={i.sku}><Card variant="outlined" sx={{p:2,borderRadius:2}}><Stack direction="row" gap={2}><Box sx={{width:48,height:48,bgcolor:"#edf6f1",color:"#278662",display:"grid",placeItems:"center",borderRadius:2}}><Inventory2Outlined/></Box><Box flex={1}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={750}>{i.nome}</Typography><Chip size="small" color={i.qtd<i.min?"error":"success"} label={`${i.qtd} un.`}/></Stack><Typography fontSize={12} color="text.secondary">SKU {i.sku} • Custo {money(i.custo)}</Typography><LinearProgress variant="determinate" color={i.qtd<i.min?"error":"success"} value={Math.min(i.qtd/i.min*70,100)} sx={{mt:1.4,height:5,borderRadius:5}}/></Box></Stack></Card></Grid>)}</Grid></Paper></Stack> }

export function Pos() { const [total,setTotal]=useState(0); return <Stack spacing={3}><PageTitle title="PDV / Vendas" subtitle="Venda produtos e serviços com baixa automática no estoque."/><Grid container spacing={3}><Grid size={{xs:12,lg:8}}><Paper sx={{...panel,p:3}}><TextField fullWidth placeholder="Busque um produto, serviço ou leia o código de barras" slotProps={{input:{startAdornment:<InputAdornment position="start"><Search/></InputAdornment>}}}/><Box sx={{textAlign:"center",py:10,color:"text.secondary"}}><PointOfSaleOutlined sx={{fontSize:55,opacity:.35}}/><Typography fontWeight={700}>Adicione itens à venda</Typography><Typography fontSize={13}>Os produtos e serviços aparecerão aqui</Typography></Box></Paper></Grid><Grid size={{xs:12,lg:4}}><Paper sx={{...panel,p:3}}><Typography fontWeight={800} fontSize={18}>Resumo da venda</Typography><Stack spacing={1.5} my={3}><Stack direction="row" justifyContent="space-between"><span>Subtotal</span><b>{money(total)}</b></Stack><Stack direction="row" justifyContent="space-between"><span>Desconto</span><span>R$ 0,00</span></Stack></Stack><Box sx={{borderTop:"1px solid #e5ebe7",pt:2}}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>Total</Typography><Typography fontSize={24} fontWeight={850} color="success.main">{money(total)}</Typography></Stack></Box><Button fullWidth size="large" variant="contained" disabled={!total} sx={{mt:3}}>Finalizar venda</Button><Button fullWidth onClick={()=>setTotal(149.9)} sx={{mt:1}}>Carregar venda de exemplo</Button></Paper></Grid></Grid></Stack> }

export function Registrations() { const [tab,setTab]=useState(0); return <Stack spacing={3}><PageTitle title="Cadastros" subtitle="Organize as informações usadas nas ordens de serviço." action={tab===0?"Nova marca":tab===1?"Novo modelo":"Novo serviço"}/><Paper sx={{...panel}}><Tabs value={tab} onChange={(_,v)=>setTab(v)} sx={{px:2,borderBottom:"1px solid #e5ebe7"}}><Tab label="Marcas"/><Tab label="Modelos"/><Tab label="Serviços"/></Tabs><Box sx={{p:3}}><Typography fontWeight={800}>{["Marcas cadastradas","Modelos por marca","Catálogo de serviços"][tab]}</Typography><Typography color="text.secondary" fontSize={13} mb={2}>{tab===1?"O modelo é sempre vinculado a uma marca.":"Cadastros disponíveis para uso nas ordens."}</Typography>{(tab===0?["Apple","Samsung","Motorola","Xiaomi"]:tab===1?["Apple — iPhone 14 Pro","Samsung — Galaxy S23","Motorola — Moto G84"]:["Troca de tela — R$ 250,00","Reparo de conector — R$ 180,00","Manutenção preventiva — R$ 220,00"]).map(x=><Stack key={x} direction="row" alignItems="center" sx={{py:1.5,borderTop:"1px solid #edf1ef"}}><Typography fontSize={14}>{x}</Typography><IconButton size="small" sx={{ml:"auto"}}><MoreHoriz/></IconButton></Stack>)}</Box></Paper></Stack> }

export function Reports() { return <Stack spacing={3}><PageTitle title="Relatórios" subtitle="Indicadores financeiros e operacionais para sua gestão."/><Grid container spacing={2}><Metric title="Receita bruta" value="R$ 31.450" detail="No mês atual" icon={<ArrowUpward/>}/><Metric title="Custos" value="R$ 12.870" detail="40,9% da receita" icon={<ArrowDownward/>}/><Metric title="Lucro estimado" value="R$ 18.580" detail="Margem de 59,1%" icon={<AssessmentIcon/>} positive/><Metric title="Ticket médio" value="R$ 748,81" detail="42 ordens finalizadas" icon={<PointOfSaleOutlined/>}/></Grid><Paper sx={{...panel,p:3,height:360}}><Typography fontWeight={800} fontSize={18}>Faturamento anual</Typography><ResponsiveContainer width="100%" height="90%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="n"/><YAxis/><Tooltip formatter={(v)=>money(Number(v))}/><Bar dataKey="v" fill="#249a6a" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></Paper></Stack> }
function AssessmentIcon(){return <ArrowUpward/>}
function PageTitle({title,subtitle,action}:{title:string,subtitle:string,action?:string}){return <Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between" gap={2}><Box><Typography variant="h4" fontWeight={800}>{title}</Typography><Typography color="text.secondary">{subtitle}</Typography></Box>{action&&<Button variant="contained" startIcon={<Add/>}>{action}</Button>}</Stack>}
