import { Add, ArrowDownward, ArrowUpward, BuildOutlined, CheckCircleOutline, Inventory2Outlined, MoreHoriz, PointOfSaleOutlined, Search, WarningAmber } from "@mui/icons-material";
import { Box, Button, Card, Chip, Grid, IconButton, InputAdornment, LinearProgress, MenuItem, Paper, Stack, Tab, Tabs, TextField, Typography } from "@mui/material";
import { useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const orders = [
  { id: "OS-1048", cliente: "Carlos Mendes", equipamento: "iPhone 14 Pro", servico: "Troca de tela", status: "Em andamento", valor: 890, data: "18/07/2026" },
  { id: "OS-1047", cliente: "Ana Paula Lima", equipamento: "Samsung S23", servico: "Reparo conector", status: "Aguardando peça", valor: 320, data: "18/07/2026" },
  { id: "OS-1046", cliente: "Tech Solutions", equipamento: "MacBook Air M2", servico: "Manutenção preventiva", status: "Finalizada", valor: 480, data: "17/07/2026" },
  { id: "OS-1045", cliente: "Marcos Rocha", equipamento: "Moto G84", servico: "Troca de bateria", status: "Aberta", valor: 260, data: "17/07/2026" },
];
const stock = [
  { nome: "Tela iPhone 14 Pro OLED", sku: "TEL-IP14P", qtd: 3, min: 5, custo: 690 },
  { nome: "Conector USB-C Samsung", sku: "CON-SAM-03", qtd: 4, min: 8, custo: 38 },
  { nome: "Bateria Moto G84", sku: "BAT-MG84", qtd: 2, min: 4, custo: 92 },
  { nome: "Álcool isopropílico 1L", sku: "INS-ALC-01", qtd: 12, min: 5, custo: 29.9 },
];
const chart = [{ n: "Jan", v: 18200 }, { n: "Fev", v: 21400 }, { n: "Mar", v: 19800 }, { n: "Abr", v: 24600 }, { n: "Mai", v: 27300 }, { n: "Jun", v: 25900 }, { n: "Jul", v: 31450 }];

const statusColor = (s: string) => s === "Finalizada" ? "success" : s === "Aguardando peça" ? "warning" : s === "Em andamento" ? "info" : "default";
const panel = { border: "1px solid #e2e9e5", borderRadius: 3, boxShadow: "0 3px 14px rgba(28,60,47,.04)" };

export function Overview() {
  return <Stack spacing={3}>
    <Box><Typography variant="h4" fontWeight={800}>Bom dia, Maurício 👋</Typography><Typography color="text.secondary">Aqui está o resumo da sua oficina hoje.</Typography></Box>
    <Grid container spacing={2}>
      <Metric title="Faturamento no mês" value="R$ 31.450,00" detail="12,5% comparado ao mês anterior" icon={<PointOfSaleOutlined />} positive />
      <Metric title="Ordens abertas" value="18" detail="6 em andamento" icon={<BuildOutlined />} />
      <Metric title="Finalizadas no mês" value="42" detail="8,2% comparado ao mês anterior" icon={<CheckCircleOutline />} positive />
      <Metric title="Estoque crítico" value="3 itens" detail="Necessitam reposição" icon={<WarningAmber />} warning />
    </Grid>
    <Grid container spacing={3}>
      <Grid size={{ xs: 12, lg: 8 }}><Paper sx={{ ...panel, p: 3 }}><Stack direction="row" justifyContent="space-between"><Box><Typography fontWeight={800} fontSize={18}>Faturamento mensal</Typography><Typography fontSize={13} color="text.secondary">Receita bruta nos últimos 7 meses</Typography></Box><Chip label="2026" size="small" /></Stack><Box sx={{ height: 270, mt: 3 }}><ResponsiveContainer><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#edf1ef"/><XAxis dataKey="n" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={v => `${v/1000}k`}/><Tooltip formatter={(v) => money(Number(v))}/><Bar dataKey="v" fill="#249a6a" radius={[6,6,0,0]} barSize={28}/></BarChart></ResponsiveContainer></Box></Paper></Grid>
      <Grid size={{ xs: 12, lg: 4 }}><Paper sx={{ ...panel, p: 3, height: "100%" }}><Typography fontWeight={800} fontSize={18}>Estoque crítico</Typography><Typography fontSize={13} color="text.secondary" mb={2}>Itens abaixo do mínimo</Typography>{stock.slice(0,3).map(i => <Box key={i.sku} sx={{ py: 1.5, borderBottom: "1px solid #edf1ef" }}><Stack direction="row" justifyContent="space-between"><Typography fontSize={13} fontWeight={700}>{i.nome}</Typography><Chip size="small" color="error" variant="outlined" label={`${i.qtd} un.`}/></Stack><Typography fontSize={11} color="text.secondary">Mínimo: {i.min} unidades</Typography></Box>)}<Button fullWidth sx={{ mt: 2 }}>Ver todo o estoque</Button></Paper></Grid>
    </Grid>
    <OrderTable title="Ordens recentes" />
  </Stack>;
}

function Metric({ title, value, detail, icon, positive, warning }: any) { return <Grid size={{ xs: 12, sm: 6, lg: 3 }}><Card sx={{ ...panel, p: 2.5 }}><Stack direction="row" justifyContent="space-between"><Box><Typography color="text.secondary" fontSize={13}>{title}</Typography><Typography fontWeight={800} fontSize={25} mt={.5}>{value}</Typography></Box><Box sx={{ width: 42, height: 42, borderRadius: 2, display: "grid", placeItems: "center", bgcolor: warning ? "#fff3e2" : "#e6f5ee", color: warning ? "#d07a18" : "#21865f" }}>{icon}</Box></Stack><Typography fontSize={11} color={positive ? "success.main" : warning ? "warning.main" : "text.secondary"} mt={1.5}>{positive && <ArrowUpward sx={{ fontSize: 12 }}/>} {detail}</Typography></Card></Grid> }

function OrderTable({ title = "Ordens de serviço" }: { title?: string }) { return <Paper sx={{ ...panel, overflow: "hidden" }}><Stack direction={{ xs: "column", sm: "row" }} sx={{ p: 2.5 }} alignItems={{ sm: "center" }} gap={2}><Box><Typography fontWeight={800} fontSize={18}>{title}</Typography><Typography fontSize={12} color="text.secondary">Acompanhe os atendimentos da oficina</Typography></Box><TextField size="small" placeholder="Buscar OS ou cliente..." sx={{ ml: { sm: "auto" } }} slotProps={{ input: { startAdornment: <InputAdornment position="start"><Search fontSize="small"/></InputAdornment> } }}/><Button variant="contained" startIcon={<Add />}>Nova OS</Button></Stack><Box sx={{ overflowX: "auto" }}><Box component="table" sx={{ width: "100%", borderCollapse: "collapse", minWidth: 800, '& th': { bgcolor: "#f7f9f8", color: "#6a7e76", fontSize: 11, textAlign: "left", py: 1.4, px: 2.5 }, '& td': { borderTop: "1px solid #edf1ef", py: 1.6, px: 2.5, fontSize: 13 } }}><thead><tr><th>ORDEM</th><th>CLIENTE / EQUIPAMENTO</th><th>SERVIÇO</th><th>STATUS</th><th>VALOR</th><th>DATA</th><th></th></tr></thead><tbody>{orders.map(o => <tr key={o.id}><td><Typography fontSize={13} fontWeight={800} color="success.main">{o.id}</Typography></td><td><b>{o.cliente}</b><br/><span style={{ color: "#778a82", fontSize: 12 }}>{o.equipamento}</span></td><td>{o.servico}</td><td><Chip size="small" color={statusColor(o.status) as any} variant="outlined" label={o.status}/></td><td><b>{money(o.valor)}</b></td><td>{o.data}</td><td><IconButton size="small"><MoreHoriz/></IconButton></td></tr>)}</tbody></Box></Box></Paper> }

export function Orders() { return <Stack spacing={3}><PageTitle title="Ordens de serviço" subtitle="Cadastre, acompanhe e finalize os atendimentos."/><OrderTable /></Stack> }

export function Inventory() { const [query,setQuery]=useState(""); const data=useMemo(()=>stock.filter(i=>i.nome.toLowerCase().includes(query.toLowerCase())),[query]); return <Stack spacing={3}><PageTitle title="Insumos e estoque" subtitle="Controle entradas, saídas e níveis mínimos." action="Novo insumo"/><Paper sx={{...panel,p:2.5}}><TextField value={query} onChange={e=>setQuery(e.target.value)} size="small" placeholder="Buscar por nome ou SKU" slotProps={{input:{startAdornment:<InputAdornment position="start"><Search/></InputAdornment>}}}/><Grid container spacing={2} mt={1}>{data.map(i=><Grid size={{xs:12,md:6}} key={i.sku}><Card variant="outlined" sx={{p:2,borderRadius:2}}><Stack direction="row" gap={2}><Box sx={{width:48,height:48,bgcolor:"#edf6f1",color:"#278662",display:"grid",placeItems:"center",borderRadius:2}}><Inventory2Outlined/></Box><Box flex={1}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={750}>{i.nome}</Typography><Chip size="small" color={i.qtd<i.min?"error":"success"} label={`${i.qtd} un.`}/></Stack><Typography fontSize={12} color="text.secondary">SKU {i.sku} • Custo {money(i.custo)}</Typography><LinearProgress variant="determinate" color={i.qtd<i.min?"error":"success"} value={Math.min(i.qtd/i.min*70,100)} sx={{mt:1.4,height:5,borderRadius:5}}/></Box></Stack></Card></Grid>)}</Grid></Paper></Stack> }

export function Pos() { const [total,setTotal]=useState(0); return <Stack spacing={3}><PageTitle title="PDV / Vendas" subtitle="Venda produtos e serviços com baixa automática no estoque."/><Grid container spacing={3}><Grid size={{xs:12,lg:8}}><Paper sx={{...panel,p:3}}><TextField fullWidth placeholder="Busque um produto, serviço ou leia o código de barras" slotProps={{input:{startAdornment:<InputAdornment position="start"><Search/></InputAdornment>}}}/><Box sx={{textAlign:"center",py:10,color:"text.secondary"}}><PointOfSaleOutlined sx={{fontSize:55,opacity:.35}}/><Typography fontWeight={700}>Adicione itens à venda</Typography><Typography fontSize={13}>Os produtos e serviços aparecerão aqui</Typography></Box></Paper></Grid><Grid size={{xs:12,lg:4}}><Paper sx={{...panel,p:3}}><Typography fontWeight={800} fontSize={18}>Resumo da venda</Typography><Stack spacing={1.5} my={3}><Stack direction="row" justifyContent="space-between"><span>Subtotal</span><b>{money(total)}</b></Stack><Stack direction="row" justifyContent="space-between"><span>Desconto</span><span>R$ 0,00</span></Stack></Stack><Box sx={{borderTop:"1px solid #e5ebe7",pt:2}}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>Total</Typography><Typography fontSize={24} fontWeight={850} color="success.main">{money(total)}</Typography></Stack></Box><Button fullWidth size="large" variant="contained" disabled={!total} sx={{mt:3}}>Finalizar venda</Button><Button fullWidth onClick={()=>setTotal(149.9)} sx={{mt:1}}>Carregar venda de exemplo</Button></Paper></Grid></Grid></Stack> }

export function Registrations() { const [tab,setTab]=useState(0); return <Stack spacing={3}><PageTitle title="Cadastros" subtitle="Organize as informações usadas nas ordens de serviço." action={tab===0?"Nova marca":tab===1?"Novo modelo":"Novo serviço"}/><Paper sx={{...panel}}><Tabs value={tab} onChange={(_,v)=>setTab(v)} sx={{px:2,borderBottom:"1px solid #e5ebe7"}}><Tab label="Marcas"/><Tab label="Modelos"/><Tab label="Serviços"/></Tabs><Box sx={{p:3}}><Typography fontWeight={800}>{["Marcas cadastradas","Modelos por marca","Catálogo de serviços"][tab]}</Typography><Typography color="text.secondary" fontSize={13} mb={2}>{tab===1?"O modelo é sempre vinculado a uma marca.":"Cadastros disponíveis para uso nas ordens."}</Typography>{(tab===0?["Apple","Samsung","Motorola","Xiaomi"]:tab===1?["Apple — iPhone 14 Pro","Samsung — Galaxy S23","Motorola — Moto G84"]:["Troca de tela — R$ 250,00","Reparo de conector — R$ 180,00","Manutenção preventiva — R$ 220,00"]).map(x=><Stack key={x} direction="row" alignItems="center" sx={{py:1.5,borderTop:"1px solid #edf1ef"}}><Typography fontSize={14}>{x}</Typography><IconButton size="small" sx={{ml:"auto"}}><MoreHoriz/></IconButton></Stack>)}</Box></Paper></Stack> }

export function Reports() { return <Stack spacing={3}><PageTitle title="Relatórios" subtitle="Indicadores financeiros e operacionais para sua gestão."/><Grid container spacing={2}><Metric title="Receita bruta" value="R$ 31.450" detail="No mês atual" icon={<ArrowUpward/>}/><Metric title="Custos" value="R$ 12.870" detail="40,9% da receita" icon={<ArrowDownward/>}/><Metric title="Lucro estimado" value="R$ 18.580" detail="Margem de 59,1%" icon={<AssessmentIcon/>} positive/><Metric title="Ticket médio" value="R$ 748,81" detail="42 ordens finalizadas" icon={<PointOfSaleOutlined/>}/></Grid><Paper sx={{...panel,p:3,height:360}}><Typography fontWeight={800} fontSize={18}>Faturamento anual</Typography><ResponsiveContainer width="100%" height="90%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="n"/><YAxis/><Tooltip formatter={(v)=>money(Number(v))}/><Bar dataKey="v" fill="#249a6a" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></Paper></Stack> }
function AssessmentIcon(){return <ArrowUpward/>}
function PageTitle({title,subtitle,action}:{title:string,subtitle:string,action?:string}){return <Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between" gap={2}><Box><Typography variant="h4" fontWeight={800}>{title}</Typography><Typography color="text.secondary">{subtitle}</Typography></Box>{action&&<Button variant="contained" startIcon={<Add/>}>{action}</Button>}</Stack>}
