import {Add,AttachMoney,DeleteOutline,EditOutlined,InfoOutlined,Search} from "@mui/icons-material";
import {Alert,Box,Button,Chip,Dialog,DialogActions,DialogContent,DialogTitle,Grid,IconButton,InputAdornment,MenuItem,Paper,Stack,TextField,Tooltip,Typography} from "@mui/material";
import {useEffect,useMemo,useState} from "react";
import {api} from "../Services/api";
import {useAuth} from "../contexts/useAuth";

type Opt={id:number|string;nome:string;marca_id?:number;modelo?:string;estoque?:number;papel?:string;ativo?:boolean};
type OS={id:number;numero:string;tecnico:string;cliente:string;atendente:string;marca:string;modelo:string;servico:string;insumo?:string;situacao:string;pago:boolean;valor_pago:number;custo:number;valor:number;data_hora?:string;tecnico_id:string;cliente_id:number;atendente_id:number;marca_id:number;modelo_id:number;servico_id:number;insumo_id?:number;defeito_relatado?:string;observacao?:string};
const situacoes=["Entrada","Pendente","Manutenção","Finalizado","Garantia"];
const localDateTime=(value:string)=>{const d=new Date(value),off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,16)};
const emptyForm={numero:"",tecnico_id:"",cliente_id:"",atendente_id:"",marca_id:"",modelo_id:"",servico_id:"",insumo_id:"",defeito_relatado:"",observacao:"",custo:"0",valor:"0",data_hora:"",situacao:"Entrada"};

export function OrdemServicoReal(){
  const {usuario}=useAuth(),admin=usuario?.papel!=="TECNICO";
  const [ordens,setOrdens]=useState<OS[]>([]),[marcas,setMarcas]=useState<Opt[]>([]),[modelos,setModelos]=useState<Opt[]>([]),[servicos,setServicos]=useState<Opt[]>([]),[insumos,setInsumos]=useState<Opt[]>([]),[tecnicos,setTecnicos]=useState<Opt[]>([]),[clientes,setClientes]=useState<Opt[]>([]),[atendentes,setAtendentes]=useState<Opt[]>([]);
  const [open,setOpen]=useState(false),[editing,setEditing]=useState<OS|null>(null),[pay,setPay]=useState<OS|null>(null),[erro,setErro]=useState(""),[q,setQ]=useState(""),[form,setForm]=useState(emptyForm),[payment,setPayment]=useState({forma:"PIX",valor:"",parcelas:"1",observacao:""});
  async function load(){try{const calls:any[]=[api.get("/os"),api.get("/marcas"),api.get("/modelos"),api.get("/servicos"),api.get("/clientes"),api.get("/atendentes"),api.get("/insumos")];if(admin)calls.push(api.get("/usuarios"));const [o,m,mo,s,c,a,i,u]=await Promise.all(calls);setOrdens(o.data);setMarcas(m.data);setModelos(mo.data);setServicos(s.data);setClientes(c.data);setAtendentes(a.data.filter((x:Opt)=>x.ativo!==false));setInsumos(i.data);if(u)setTecnicos(u.data.filter((x:Opt)=>x.ativo&&["TECNICO","ADMIN","PROPRIETARIO"].includes(x.papel||"")))}catch(e:any){setErro(e.response?.data?.erro||"Não foi possível carregar as ordens")}}
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>ordens.filter(o=>`${o.numero} ${o.cliente} ${o.tecnico}`.toLowerCase().includes(q.toLowerCase())),[ordens,q]);
  const servicoUsaTampa=/tampa traseira.*iphone/i.test(servicos.find(s=>String(s.id)===String(form.servico_id))?.nome||"");
  async function save(){try{const body={...form,tecnico_id:form.tecnico_id||usuario?.id,cliente_id:Number(form.cliente_id),atendente_id:Number(form.atendente_id),marca_id:Number(form.marca_id),modelo_id:Number(form.modelo_id),servico_id:Number(form.servico_id),insumo_id:servicoUsaTampa?Number(form.insumo_id):null,custo:Number(form.custo)||0,valor:Number(form.valor)||0};let id=editing?.id;if(editing)await api.patch(`/os/${editing.id}`,body);else{const created=await api.post("/os",body);id=created.data.id;await api.patch(`/os/${id}`,{custo:body.custo,valor:body.valor})}if(id)await api.patch(`/os/${id}/data-hora`,{data_hora:form.data_hora?new Date(form.data_hora).toISOString():null});setOpen(false);setEditing(null);await load()}catch(e:any){setErro(e.response?.data?.erro||"Não foi possível salvar a OS")}}
  function edit(o:OS){setEditing(o);setForm({numero:o.numero,tecnico_id:String(o.tecnico_id||""),cliente_id:String(o.cliente_id||""),atendente_id:String(o.atendente_id||""),marca_id:String(o.marca_id||""),modelo_id:String(o.modelo_id||""),servico_id:String(o.servico_id||""),insumo_id:String(o.insumo_id||""),defeito_relatado:o.defeito_relatado||"",observacao:o.observacao||"",custo:String(o.custo||0),valor:String(o.valor||0),data_hora:o.data_hora?localDateTime(o.data_hora):"",situacao:o.situacao});setOpen(true)}
  async function remove(o:OS){if(!window.confirm(`Excluir a OS ${o.numero}?`))return;try{await api.delete(`/os/${o.id}`);await load()}catch(e:any){setErro(e.response?.data?.erro||"Não foi possível excluir a OS")}}
  async function confirmPay(){if(!pay)return;try{await api.post(`/os/${pay.id}/pagamento`,{...payment,valor:Number(payment.valor),parcelas:Number(payment.parcelas)});setPay(null);await load()}catch(e:any){setErro(e.response?.data?.erro||"Não foi possível confirmar o pagamento")}}
  function newOS(){setEditing(null);setForm({...emptyForm,data_hora:localDateTime(new Date().toISOString())});setErro("");setOpen(true)}
  return <Stack spacing={3}>
    <Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between"><Box><Typography variant="h4" fontWeight={800}>Ordens de serviço</Typography><Typography color="text.secondary">O faturamento só é confirmado depois do pagamento.</Typography></Box><Button variant="contained" startIcon={<Add/>} onClick={newOS}>Nova OS</Button></Stack>
    {erro&&<Alert severity="error" onClose={()=>setErro("")}>{erro}</Alert>}
    <Paper sx={{border:"1px solid #e2e9e5",borderRadius:3,overflow:"hidden"}}><Box sx={{p:1.5}}><TextField size="small" value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar OS, cliente ou técnico" slotProps={{input:{startAdornment:<InputAdornment position="start"><Search/></InputAdornment>}}}/></Box><Box sx={{overflowX:"auto"}}><Box component="table" sx={{width:"100%",minWidth:1070,borderCollapse:"collapse",tableLayout:"fixed",'& th':{bgcolor:"#f7f9f8",px:1,py:1.2,textAlign:"left",fontSize:10,color:"#60736b"},'& td':{px:1,py:1.2,borderTop:"1px solid #edf1ef",fontSize:12,overflow:"hidden",textOverflow:"ellipsis"}}}><thead><tr><th style={{width:65}}>OS</th><th style={{width:105}}>DATA/HORA</th><th style={{width:95}}>TÉCNICO</th><th style={{width:115}}>CLIENTE</th><th style={{width:95}}>ATENDENTE</th><th style={{width:125}}>MARCA / MODELO</th><th style={{width:115}}>SERVIÇO</th><th style={{width:45}}>DEF.</th><th style={{width:85}}>SITUAÇÃO</th><th style={{width:90}}>PAGTO.</th><th style={{width:70}}>AÇÕES</th></tr></thead><tbody>{filtered.map(o=><tr key={o.id}><td><b>{o.numero}</b></td><td>{o.data_hora?<><b>{new Date(o.data_hora).toLocaleDateString("pt-BR")}</b><br/><span style={{color:"#6d7d76",fontSize:11}}>{new Date(o.data_hora).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</span></>:"—"}</td><td title={o.tecnico}>{o.tecnico}</td><td title={o.cliente}>{o.cliente}</td><td title={o.atendente}>{o.atendente}</td><td title={`${o.marca} / ${o.modelo}`}><b>{o.marca}</b><br/><span style={{color:"#6d7d76",fontSize:11}}>{o.modelo}</span></td><td title={o.servico}>{o.servico}</td><td><Tooltip title={o.defeito_relatado||"Nenhum defeito descrito"} arrow><IconButton size="small"><InfoOutlined fontSize="small"/></IconButton></Tooltip></td><td><Chip size="small" label={o.situacao}/></td><td>{o.pago?<Tooltip title={`Pago: ${Number(o.valor_pago).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}`}><Chip size="small" color="success" label="Pago"/></Tooltip>:o.situacao==="Finalizado"&&admin?<Tooltip title="Finalizar pagamento"><IconButton size="small" color="success" onClick={()=>{setPayment({forma:"PIX",valor:"",parcelas:"1",observacao:""});setPay(o)}}><AttachMoney fontSize="small"/></IconButton></Tooltip>:<Chip size="small" label="Pendente" variant="outlined"/>}</td><td><Tooltip title="Editar OS"><IconButton size="small" onClick={()=>edit(o)}><EditOutlined fontSize="small"/></IconButton></Tooltip><Tooltip title={o.pago?"OS paga não pode ser excluída":"Excluir OS"}><span><IconButton size="small" color="error" disabled={o.pago} onClick={()=>remove(o)}><DeleteOutline fontSize="small"/></IconButton></span></Tooltip></td></tr>)}</tbody></Box></Box></Paper>
    <Dialog open={open} onClose={()=>{setOpen(false);setEditing(null)}} fullWidth maxWidth="md"><DialogTitle>{editing?`Editar ordem ${editing.numero}`:"Nova ordem de serviço"}</DialogTitle><DialogContent><Grid container spacing={2} mt={1}>
      <Grid size={{xs:12,sm:4}}><TextField fullWidth label="Nr OS" required value={form.numero} disabled={!!editing} onChange={e=>setForm({...form,numero:e.target.value})}/></Grid>
      {admin&&<Grid size={{xs:12,sm:4}}><TextField select fullWidth label="Técnico" required value={form.tecnico_id} onChange={e=>setForm({...form,tecnico_id:e.target.value})}>{tecnicos.map(t=><MenuItem key={t.id} value={t.id}>{t.nome}</MenuItem>)}</TextField></Grid>}
      <Grid size={{xs:12,sm:4}}><TextField select fullWidth label="Atendente" required value={form.atendente_id} onChange={e=>setForm({...form,atendente_id:e.target.value})}>{atendentes.map(a=><MenuItem key={a.id} value={a.id}>{a.nome}</MenuItem>)}</TextField></Grid>
      <Grid size={{xs:12,sm:6}}><TextField select fullWidth label="Cliente" required value={form.cliente_id} onChange={e=>setForm({...form,cliente_id:e.target.value})}>{clientes.map(c=><MenuItem key={c.id} value={c.id}>{c.nome}</MenuItem>)}</TextField></Grid>
      <Grid size={{xs:12,sm:6}}><TextField select fullWidth label="Situação" value={form.situacao} onChange={e=>setForm({...form,situacao:e.target.value})}>{situacoes.map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField></Grid>
      <Grid size={{xs:12,sm:4}}><TextField select fullWidth label="Marca" required value={form.marca_id} onChange={e=>setForm({...form,marca_id:e.target.value,modelo_id:""})}>{marcas.map(m=><MenuItem key={m.id} value={m.id}>{m.nome}</MenuItem>)}</TextField></Grid>
      <Grid size={{xs:12,sm:4}}><TextField select fullWidth label="Modelo" required value={form.modelo_id} onChange={e=>setForm({...form,modelo_id:e.target.value})}>{modelos.filter(m=>String(m.marca_id)===String(form.marca_id)).map(m=><MenuItem key={m.id} value={m.id}>{m.nome}</MenuItem>)}</TextField></Grid>
      <Grid size={{xs:12,sm:4}}><TextField select fullWidth label="Serviço" required value={form.servico_id} onChange={e=>setForm({...form,servico_id:e.target.value})}>{servicos.map(s=><MenuItem key={s.id} value={s.id}>{s.nome}</MenuItem>)}</TextField></Grid>
      {servicoUsaTampa&&<Grid size={{xs:12}}><TextField select fullWidth required label="Tampa traseira utilizada" value={form.insumo_id} onChange={e=>setForm({...form,insumo_id:e.target.value})} helperText="Será baixada do estoque quando a OS for finalizada">{insumos.filter(i=>(i.modelo||"").toLowerCase()===((modelos.find(m=>String(m.id)===String(form.modelo_id))?.nome||"").toLowerCase())).map(i=><MenuItem key={i.id} value={i.id} disabled={Number(i.estoque)<=0}>{i.nome} — estoque: {i.estoque}</MenuItem>)}</TextField></Grid>}
      <Grid size={{xs:12,sm:6}}><TextField fullWidth type="number" label="Custo do insumo" value={form.custo} onChange={e=>setForm({...form,custo:e.target.value})} slotProps={{htmlInput:{min:0,step:"0.01"}}}/></Grid>
      <Grid size={{xs:12,sm:6}}><TextField fullWidth type="number" label="Valor da OS" value={form.valor} onChange={e=>setForm({...form,valor:e.target.value})} slotProps={{htmlInput:{min:0,step:"0.01"}}}/></Grid>
      <Grid size={{xs:12,sm:6}}><TextField fullWidth type="datetime-local" label="Data/Hora da OS" value={form.data_hora} onChange={e=>setForm({...form,data_hora:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/></Grid>
      <Grid size={{xs:12}}><TextField fullWidth label="Defeito relatado" value={form.defeito_relatado} onChange={e=>setForm({...form,defeito_relatado:e.target.value})}/></Grid>
    </Grid></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="contained" onClick={save}>Salvar OS</Button></DialogActions></Dialog>
    <Dialog open={!!pay} onClose={()=>setPay(null)} fullWidth maxWidth="sm"><DialogTitle>Finalizar pagamento • {pay?.numero}</DialogTitle><DialogContent><Stack spacing={2} mt={1}><Alert severity="info">Somente após confirmar este pagamento a OS entrará no faturamento.</Alert><TextField select label="Forma de pagamento" value={payment.forma} onChange={e=>setPayment({...payment,forma:e.target.value})}>{[["PIX","Pix"],["DINHEIRO","Dinheiro"],["DEBITO","Cartão de débito"],["CREDITO","Cartão de crédito"],["TRANSFERENCIA","Transferência"]].map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField><TextField label="Valor recebido" type="number" value={payment.valor} onChange={e=>setPayment({...payment,valor:e.target.value})}/>{payment.forma==="CREDITO"&&<TextField label="Parcelas" type="number" value={payment.parcelas} onChange={e=>setPayment({...payment,parcelas:e.target.value})}/>}<TextField label="Observação" value={payment.observacao} onChange={e=>setPayment({...payment,observacao:e.target.value})}/></Stack></DialogContent><DialogActions><Button onClick={()=>setPay(null)}>Cancelar</Button><Button variant="contained" color="success" onClick={confirmPay}>Confirmar pagamento</Button></DialogActions></Dialog>
  </Stack>
}
