import {Add,DeleteOutline,History,PointOfSaleOutlined,PrintOutlined,Remove,Search,ShoppingCartOutlined} from "@mui/icons-material";
import {Alert,Box,Button,Chip,Dialog,DialogActions,DialogContent,DialogTitle,Divider,Grid,IconButton,InputAdornment,MenuItem,Paper,Stack,Tab,Tabs,TextField,Tooltip,Typography} from "@mui/material";
import {useEffect,useMemo,useState} from "react";
import {api} from "../Services/api";
import {useAuth} from "../contexts/useAuth";

type Produto={id:number;nome:string;sku?:string;estoque?:number;preco_venda?:number;preco?:number;custo_medio?:number;custo?:number};
type Cliente={id:number;nome:string};
type Carrinho={chave:string;id:number;tipo:"INSUMO"|"SERVICO";nome:string;quantidade:number;valor_unitario:number;estoque?:number};
type Venda={id:number;numero:string;cliente?:string;vendedor?:string;total:number;forma_pagamento:string;parcelas:number;status:string;criado_em:string;itens:any[]};
const money=(v:number)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export function PdvReal(){
 const {usuario}=useAuth(),admin=usuario?.papel==="ADMIN"||usuario?.papel==="PROPRIETARIO";
 const [insumos,setInsumos]=useState<Produto[]>([]),[servicos,setServicos]=useState<Produto[]>([]),[clientes,setClientes]=useState<Cliente[]>([]),[vendas,setVendas]=useState<Venda[]>([]),[carrinho,setCarrinho]=useState<Carrinho[]>([]),[busca,setBusca]=useState(""),[tab,setTab]=useState(0),[erro,setErro]=useState(""),[checkout,setCheckout]=useState(false),[salvando,setSalvando]=useState(false),[ultima,setUltima]=useState<Venda|null>(null);
 const [pagamento,setPagamento]=useState({cliente_id:"",desconto:"0",forma_pagamento:"PIX",parcelas:"1",observacao:""});
 async function load(){try{const [i,s,c,v]=await Promise.all([api.get("/insumos"),api.get("/servicos"),api.get("/clientes"),api.get("/vendas")]);setInsumos(i.data);setServicos(s.data);setClientes(c.data);setVendas(v.data)}catch(e:any){setErro(e.response?.data?.erro||"Não foi possível carregar o PDV")}}
 useEffect(()=>{load()},[]);
 const catalogo=useMemo(()=>{const fonte=tab===1?insumos:tab===2?servicos:[...insumos,...servicos];return fonte.filter(p=>`${p.nome} ${p.sku||""}`.toLowerCase().includes(busca.toLowerCase()))},[tab,insumos,servicos,busca]);
 const subtotal=carrinho.reduce((s,i)=>s+i.quantidade*i.valor_unitario,0),desconto=Math.max(0,Number(pagamento.desconto)||0),total=Math.max(0,subtotal-desconto);
 function tipoProduto(p:Produto):"INSUMO"|"SERVICO"{return p.sku!==undefined?"INSUMO":"SERVICO"}
 function adicionar(p:Produto){const tipo=tipoProduto(p),chave=`${tipo}-${p.id}`,estoque=Number(p.estoque||0);if(tipo==="INSUMO"&&estoque<=0)return setErro(`${p.nome} está sem estoque`);setCarrinho(atual=>{const existe=atual.find(i=>i.chave===chave);if(existe){if(tipo==="INSUMO"&&existe.quantidade>=estoque)return atual;return atual.map(i=>i.chave===chave?{...i,quantidade:i.quantidade+1}:i)}return[...atual,{chave,id:p.id,tipo,nome:p.nome,quantidade:1,valor_unitario:Number(tipo==="INSUMO"?p.preco_venda:p.preco)||0,estoque:tipo==="INSUMO"?estoque:undefined}]})}
 function quantidade(chave:string,n:number){setCarrinho(c=>c.map(i=>i.chave===chave?{...i,quantidade:Math.max(1,Math.min(n,i.estoque??999))}:i))}
 async function finalizar(){if(!carrinho.length||total<=0)return;try{setSalvando(true);setErro("");const {data}=await api.post("/vendas",{...pagamento,cliente_id:pagamento.cliente_id||null,desconto,parcelas:Number(pagamento.parcelas),itens:carrinho.map(i=>({id:i.id,tipo:i.tipo,quantidade:i.quantidade,valor_unitario:i.valor_unitario}))});const venda={...data,itens:carrinho};setUltima(venda);setCarrinho([]);setCheckout(false);setPagamento({cliente_id:"",desconto:"0",forma_pagamento:"PIX",parcelas:"1",observacao:""});await load()}catch(e:any){setErro(e.response?.data?.erro||"Não foi possível finalizar a venda")}finally{setSalvando(false)}}
 async function cancelar(v:Venda){if(!window.confirm(`Cancelar a venda ${v.numero} e devolver os itens ao estoque?`))return;try{await api.post(`/vendas/${v.id}/cancelar`);await load()}catch(e:any){setErro(e.response?.data?.erro||"Não foi possível cancelar a venda")}}
 function imprimir(v:any){const itens=v.itens||[],w=window.open("","_blank","width=420,height=650");if(!w)return;w.document.write(`<html><head><title>${v.numero}</title><style>body{font-family:Arial;padding:24px;color:#1f342c}h2{text-align:center}table{width:100%;border-collapse:collapse}td,th{padding:7px;border-bottom:1px dashed #bbb;text-align:left}.right{text-align:right}.total{font-size:18px;font-weight:bold}</style></head><body><h2>COMPROVANTE DE VENDA</h2><p><b>${v.numero}</b><br>${new Date(v.criado_em||Date.now()).toLocaleString("pt-BR")}</p><table><tr><th>Item</th><th>Qtd.</th><th class="right">Valor</th></tr>${itens.map((i:any)=>`<tr><td>${i.nome||i.descricao}</td><td>${i.quantidade}</td><td class="right">${money(Number(i.valor_unitario)*Number(i.quantidade))}</td></tr>`).join("")}</table><p class="right total">Total: ${money(Number(v.total||total))}</p><p>Pagamento: ${v.forma_pagamento||pagamento.forma_pagamento}</p><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
 return <Stack spacing={3}>
  <Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between" gap={2}><Box><Typography variant="h4" fontWeight={800}>PDV / Vendas</Typography><Typography color="text.secondary">Venda produtos e serviços com baixa automática no estoque.</Typography></Box><Chip icon={<PointOfSaleOutlined/>} label="Caixa online" color="success" variant="outlined" sx={{alignSelf:{sm:"center"}}}/></Stack>
  {erro&&<Alert severity="error" onClose={()=>setErro("")}>{erro}</Alert>}{ultima&&<Alert severity="success" action={<Button color="inherit" size="small" startIcon={<PrintOutlined/>} onClick={()=>imprimir(ultima)}>Imprimir</Button>}>Venda {ultima.numero} concluída com sucesso.</Alert>}
  <Grid container spacing={3}><Grid size={{xs:12,lg:8}}><Paper sx={{border:"1px solid #e2e9e5",borderRadius:3,overflow:"hidden"}}><Tabs value={tab} onChange={(_,v)=>setTab(v)} sx={{px:2,borderBottom:"1px solid #e6ece8"}}><Tab label="Todos"/><Tab label="Produtos / Insumos"/><Tab label="Serviços"/></Tabs><Box p={2}><TextField fullWidth size="small" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar produto, serviço ou SKU" slotProps={{input:{startAdornment:<InputAdornment position="start"><Search/></InputAdornment>}}}/><Grid container spacing={1.5} mt={.5}>{catalogo.map(p=>{const tipo=tipoProduto(p),semEstoque=tipo==="INSUMO"&&Number(p.estoque)<=0;return <Grid size={{xs:12,sm:6,md:4}} key={`${tipo}-${p.id}`}><Paper variant="outlined" sx={{p:1.8,borderRadius:2,height:"100%",opacity:semEstoque ? .55 : 1}}><Typography fontWeight={750} fontSize={13}>{p.nome}</Typography><Typography fontSize={11} color="text.secondary" minHeight={18}>{tipo==="INSUMO"?`${p.sku} • Estoque ${p.estoque}`:"Serviço"}</Typography><Stack direction="row" alignItems="center" mt={1}><Typography fontWeight={850} color="success.main">{money(Number(tipo==="INSUMO"?p.preco_venda:p.preco))}</Typography><IconButton size="small" color="primary" disabled={semEstoque} onClick={()=>adicionar(p)} sx={{ml:"auto",bgcolor:"#e8f6ef"}}><Add/></IconButton></Stack></Paper></Grid>})}{!catalogo.length&&<Grid size={{xs:12}}><Typography color="text.secondary" textAlign="center" py={6}>Nenhum item encontrado.</Typography></Grid>}</Grid></Box></Paper></Grid>
  <Grid size={{xs:12,lg:4}}><Paper sx={{border:"1px solid #dce7e1",borderRadius:3,overflow:"hidden",position:{lg:"sticky"},top:{lg:92}}}><Stack direction="row" alignItems="center" gap={1} p={2} bgcolor="#f2faf6"><ShoppingCartOutlined color="success"/><Typography fontWeight={850}>Carrinho</Typography><Chip size="small" label={carrinho.length} sx={{ml:"auto"}}/></Stack><Box sx={{maxHeight:360,overflowY:"auto"}}>{carrinho.map(i=><Box key={i.chave} p={1.6} borderTop="1px solid #edf1ef"><Stack direction="row" gap={1}><Box flex={1}><Typography fontSize={13} fontWeight={700}>{i.nome}</Typography><Typography fontSize={11} color="text.secondary">{money(i.valor_unitario)} cada</Typography></Box><IconButton size="small" color="error" onClick={()=>setCarrinho(c=>c.filter(x=>x.chave!==i.chave))}><DeleteOutline fontSize="small"/></IconButton></Stack><Stack direction="row" alignItems="center" mt={1}><IconButton size="small" onClick={()=>quantidade(i.chave,i.quantidade-1)}><Remove fontSize="small"/></IconButton><Typography width={30} textAlign="center" fontWeight={800}>{i.quantidade}</Typography><IconButton size="small" onClick={()=>quantidade(i.chave,i.quantidade+1)}><Add fontSize="small"/></IconButton><Typography ml="auto" fontWeight={800}>{money(i.quantidade*i.valor_unitario)}</Typography></Stack></Box>)}{!carrinho.length&&<Box textAlign="center" py={7} color="text.secondary"><ShoppingCartOutlined sx={{fontSize:45,opacity:.3}}/><Typography fontSize={13}>Carrinho vazio</Typography></Box>}</Box><Box p={2} borderTop="1px solid #dfe8e3"><Stack direction="row" justifyContent="space-between"><Typography>Subtotal</Typography><Typography fontWeight={700}>{money(subtotal)}</Typography></Stack><Stack direction="row" justifyContent="space-between" mt={1}><Typography fontWeight={850} fontSize={17}>Total</Typography><Typography fontWeight={900} fontSize={22} color="success.main">{money(subtotal)}</Typography></Stack><Button fullWidth size="large" variant="contained" sx={{mt:2}} disabled={!carrinho.length} onClick={()=>setCheckout(true)}>Finalizar venda</Button></Box></Paper></Grid></Grid>
  <Paper sx={{border:"1px solid #e2e9e5",borderRadius:3,overflow:"hidden"}}><Stack direction="row" alignItems="center" gap={1} p={2}><History color="primary"/><Typography fontWeight={850}>Vendas recentes</Typography></Stack><Box sx={{overflowX:"auto"}}><Box component="table" sx={{width:"100%",minWidth:760,borderCollapse:"collapse",'& th':{bgcolor:"#f7f9f8",p:1.3,textAlign:"left",fontSize:11,color:"text.secondary"},'& td':{p:1.3,borderTop:"1px solid #edf1ef",fontSize:13}}}><thead><tr><th>VENDA</th><th>DATA</th><th>CLIENTE</th><th>VENDEDOR</th><th>PAGAMENTO</th><th>TOTAL</th><th>STATUS</th><th></th></tr></thead><tbody>{vendas.map(v=><tr key={v.id}><td><b>{v.numero}</b></td><td>{new Date(v.criado_em).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})}</td><td>{v.cliente||"Consumidor final"}</td><td>{v.vendedor||"—"}</td><td>{v.forma_pagamento}{v.parcelas>1?` • ${v.parcelas}x`:""}</td><td><b>{money(v.total)}</b></td><td><Chip size="small" color={v.status==="CONCLUIDA"?"success":"default"} label={v.status}/></td><td><Tooltip title="Imprimir"><IconButton size="small" onClick={()=>imprimir(v)}><PrintOutlined/></IconButton></Tooltip>{admin&&v.status==="CONCLUIDA"&&<Tooltip title="Cancelar venda"><IconButton size="small" color="error" onClick={()=>cancelar(v)}><DeleteOutline/></IconButton></Tooltip>}</td></tr>)}</tbody></Box></Box></Paper>
  <Dialog open={checkout} onClose={()=>!salvando&&setCheckout(false)} fullWidth maxWidth="sm"><DialogTitle>Finalizar venda</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField select label="Cliente (opcional)" value={pagamento.cliente_id} onChange={e=>setPagamento({...pagamento,cliente_id:e.target.value})}><MenuItem value="">Consumidor final</MenuItem>{clientes.map(c=><MenuItem key={c.id} value={c.id}>{c.nome}</MenuItem>)}</TextField><Grid container spacing={2}><Grid size={{xs:12,sm:6}}><TextField select fullWidth label="Forma de pagamento" value={pagamento.forma_pagamento} onChange={e=>setPagamento({...pagamento,forma_pagamento:e.target.value})}>{[["PIX","PIX"],["DINHEIRO","Dinheiro"],["DEBITO","Débito"],["CREDITO","Crédito"],["TRANSFERENCIA","Transferência"]].map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField></Grid><Grid size={{xs:12,sm:6}}><TextField fullWidth type="number" label="Parcelas" disabled={pagamento.forma_pagamento!=="CREDITO"} value={pagamento.parcelas} onChange={e=>setPagamento({...pagamento,parcelas:e.target.value})} slotProps={{htmlInput:{min:1,max:24}}}/></Grid></Grid><TextField type="number" label="Desconto" value={pagamento.desconto} onChange={e=>setPagamento({...pagamento,desconto:e.target.value})} slotProps={{htmlInput:{min:0,max:subtotal,step:.01}}}/><TextField label="Observação" multiline minRows={2} value={pagamento.observacao} onChange={e=>setPagamento({...pagamento,observacao:e.target.value})}/><Divider/><Stack spacing={.7}><Stack direction="row" justifyContent="space-between"><span>Subtotal</span><b>{money(subtotal)}</b></Stack><Stack direction="row" justifyContent="space-between"><span>Desconto</span><span>- {money(desconto)}</span></Stack><Stack direction="row" justifyContent="space-between"><Typography fontWeight={900}>Total a pagar</Typography><Typography fontWeight={900} fontSize={22} color="success.main">{money(total)}</Typography></Stack></Stack></Stack></DialogContent><DialogActions><Button onClick={()=>setCheckout(false)} disabled={salvando}>Cancelar</Button><Button variant="contained" onClick={finalizar} disabled={salvando||total<=0}>{salvando?"Finalizando...":"Confirmar pagamento"}</Button></DialogActions></Dialog>
 </Stack>
}
